import '../models/location_model.dart';

class LocationRepository {
  Stream<List<LocationModel>> watchAll() => Stream.value(_locations);

  static const _locations = <LocationModel>[
    LocationModel(
      id: 'gedung-1-lantai-b',
      name: 'Gedung 1 Lantai B',
      building: 'Gedung 1',
      floor: -1,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-1-lantai-gf',
      name: 'Gedung 1 Lantai GF',
      building: 'Gedung 1',
      floor: 0,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-1-lantai-1',
      name: 'Gedung 1 Lantai 1',
      building: 'Gedung 1',
      floor: 1,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-1-lantai-2',
      name: 'Gedung 1 Lantai 2',
      building: 'Gedung 1',
      floor: 2,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-1-lantai-3',
      name: 'Gedung 1 Lantai 3',
      building: 'Gedung 1',
      floor: 3,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-2-lantai-b',
      name: 'Gedung 2 Lantai B',
      building: 'Gedung 2',
      floor: -1,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-2-lantai-gf',
      name: 'Gedung 2 Lantai GF',
      building: 'Gedung 2',
      floor: 0,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-2-lantai-1',
      name: 'Gedung 2 Lantai 1',
      building: 'Gedung 2',
      floor: 1,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-2-lantai-2',
      name: 'Gedung 2 Lantai 2',
      building: 'Gedung 2',
      floor: 2,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'gedung-2-lantai-3',
      name: 'Gedung 2 Lantai 3',
      building: 'Gedung 2',
      floor: 3,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'perpustakaan-gedung-1-lantai-gf',
      name: 'Perpustakaan Gedung 1 Lantai GF',
      building: 'Perpustakaan',
      floor: 0,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'kantin-basement',
      name: 'Kantin (Basement)',
      building: 'Kantin',
      floor: -1,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'parkiran-motor',
      name: 'Parkiran Motor',
      building: 'Parkiran (Basement)',
      floor: -1,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
    LocationModel(
      id: 'parkiran-mobil',
      name: 'Parkiran Mobil',
      building: 'Parkiran (Basement)',
      floor: -1,
      latitude: -6.2607827,
      longitude: 106.6184306,
      createdAt: null,
    ),
  ];
}
